### ISSUE TITLE
[💄FRONT] customer메인화면과 웨이팅 등록 화면 연결

### ISSUE THREAD

**Issue by kim201621123** [nbc-team-gumi/goodbite-react#37]
## 💬 설명

customer메인화면과 웨이팅 등록 화면 연결작업

## ☑️TO-DO

- [x] 메인화면에 이동 버튼 추가
- [x] 메인화면에서 웨이팅 등록 화면으로 restaurantId값 전달
- [x] 등록 기능 작동 확인
