### ISSUE TITLE
[♻️ REFACTOR] 레스토랑 리팩토링

### ISSUE THREAD

**Issue by haeuni00** [nbc-team-gumi/goodbite-react#73]
## 💬 설명
백엔드 수정에 대한 레스토랑 리팩토링

## ☑️TO-DO
- [ ] 가게 등록, 수정 시 카테고리는 목록에서 선택하도록
- [ ] 가게 등록, 수정 시 이미지 파일 첨부 형식으로 변경
- [ ] 가게 등록, 수정 시 주소 API 추가
